require 'faker'

# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)
games = [
  "The Legend of Zelda: Majora's Mask",
  "Shadow of the Colossus",
  "Journey",
  "The Legend of Zelda: Breath of the Wild",
  "Knights of the Old Republic II: The Sith Lords",
  "The Legend of Zelda: Ocarina of Time",
  "The Elder Scrolls III: Morrowind*",
  "The Legend of Zelda: The Wind Waker",
  "Halo",
  "Half-Life 2*",
  "Bloodborne",
  "Furi",
  "Persona 5",
  "Rocket League",
  "The Last of Us",
  "Knights of the Old Republic I",
  "Metroid Prime",
  "Phastasy Star Online Episode I & II",
  "Donkey Kong Country",
  "Super Smash Bros. Melee",
  "Super Mario Odyssey",
  "Donkey Kong Country 2: Diddy's Kong Quest",
  "Final Fantasy X",
  "The Last Guardian",
  "The Legend of Zelda: A Link to the Past",
  "Overwatch",
  "Bioshock",
  "Uncharted 4: A Thief's End",
  "Grand Theft Auto IV",
  "Bastion",
  "Half-Life",
  "Halo 2",
  "Resident Evil 4",
  "Pikmin",
  "Grand Theft Auto IV: Episodes from Liberty City",
  "Super Meat Boy!",
  "Luigi's Mansion",
  "Darkest Dungeon",
  "Papers, Please",
  "Bioshock Infinite",
  "The Elder Scrolls IV: Oblivion",
  "Jurassic Park",
  "Beyond Good & Evil",
  "Animal Crossing",
  "Destiny 2",
  "Empire: Total War",
  "Shadow of Mordor",
  "Grand Theft Auto V",
  "The Elder Scrolls V: Skyrim",
  "Nom Nom Galaxy",
  "The Legend of Zelda: Four Swords Adventures",
  "Jurassic Park, Part 2: The Chaos Continues",
  "Pilotwings",
  "Beautiful Katamari",
  "Disgaea 5: Alliance of Vengeance",
  "Mickey Mania",
  "Grow Home",
  "NOT A HERO",
  "Chromehounds",
  "Topspin 4",
  "Mariokart Double Dash",
  "Fable",
  "Mount & Blade: Warband",
  "Crusader Kings 2",
  "Prince of Persia",
  "Kerbal Space Program",
  "Tom Clancy's Splinter Cell",
  "Pillars of Eternity",
  "LIMBO",
  "Viva Pinata",
  "Final Fantasy XIII",
  "Forza 4",
  "Abzû",
  "Fable II",
  "Batman: Arkham Asylum",
  "Viewtiful Joe",
  "Crimson Skies: High Road to Revenge",
  "Horizon Zero Dawn",
  "HELLDIVERS",
  "Deus Ex: Human Revolution*",
  "Super Mario All Stars*",
  "Lovers in a Dangerous Spacetime",
  "Stories: The Path of Destinies",
  "Final Fantasy XV",
  "Just Cause 3",
  "From Dust",
  "Tiny Toon Buster Busts Loose",
  "inFamous Second Son",
  "Antichamber",
  "Fez",
  "Europa Universalis III",
  "Mini Metro",
  "Passpartout",
  "Luftrausers",
  "Endless Legend",
  "Final Fantasy Crystal Chronicles",
  "Sonic Adventures 2 Battle",
  "Octodad: Deadlist Catch",
  "Mount & Blade: With Fire and Sword",
  "Grow Up",
  "Garry's Mod",
  "FIFA 13",
  "Soul Caliber II",
  "Luna's Wandering Stars",
  "Toy Story",
  "Indiana Jones Greatest Adventures",
  "Magicka 2",
  "Phastasy Star Universe",
  "Star Wars Rogue Leader",
  "Super Star Wars Series*",
  "Harvest Moon: A Wonderful Life",
  "Saints Row: Gat out of Hell",
  "Counterstrike: Source",
  "Panzer Dragoon Orta",
  "Blinx the Time Sweeper",
  "Perfect Dark: Zero",
  "Oddworld Munch's Oddysee",
  "Mortal Kombat: Deadly Alliance",
  "Gauntlet: Dark Legacy",
  "Crazy Taxi 3: High Roller",
  "We're Back: A Dinosaurs Story",
  "Yoshi Safari",
  "Primal Rage",
  "Tricky Towers",
  "Tropico 5",
  "TorqueL",
  "007: Nightfire",
  "Dream TV",
  "All-Star Baseball 2004",
  "Toys"
]

company_names = []
10.times do
  company_names << Faker::Company.name
end

platform = ["PlayStation", "Nintendo Switch", "Xbox", "PC"]

games.each do |g|
  Game.create!(
    title: g,
    publisher: company_names.sample,
    platform: platform.sample
  )
end
